{application,floki,
             [{registered,[]},
              {description,"A HTML parser and searcher.\n\nYou can search inside HTML documents using CSS selectors.\n"},
              {applications,[kernel,stdlib,elixir,mochiweb]},
              {vsn,"0.7.1"},
              {modules,['Elixir.Floki','Elixir.Floki.AttributeSelector',
                        'Elixir.Floki.Combinator','Elixir.Floki.DeepText',
                        'Elixir.Floki.FilterOut','Elixir.Floki.Finder',
                        'Elixir.Floki.FlatText','Elixir.Floki.Parser',
                        'Elixir.Floki.Selector','Elixir.Floki.SelectorParser',
                        'Elixir.Floki.SelectorTokenizer',
                        floki_selector_lexer]}]}.